import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col h-screen w-screen justify-center items-center bg-blue-400">
        <h1 className="text-white text-4xl">Tailwind Template</h1>
      </main>
      <footer></footer>
    </div>
  );
}
